"""empty message

Revision ID: 2e4ad8df12d5
Revises: c5988fdbc98a
Create Date: 2021-06-15 21:10:04.078000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e4ad8df12d5'
down_revision = 'c5988fdbc98a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('issues', sa.Column('assigned_to', sa.String(length=60), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('issues', 'assigned_to')
    # ### end Alembic commands ###
